source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'html-proofer'
gem 'rouge'
gem 'uglifier'
gem 'sprockets', '~> 3.7'
gem 'kramdown-parser-gfm', '~> 1.1'
